filebeat.config:
  modules:
  - module: nginx
  - module: system
  - module: docker

processors:
- add_host_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOST:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'