filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_host_metadata: ~

setup.kibana:
  host: '${KIBANA_HOST}'
setup.template:
  name: "filebeat"
  pattern: "filebeat-*"

setup.ilm.enabled: false
ilm.enabled: false

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOST:elasticsearch:9200}'
  index: "%{[agent.type]}-%{[agent.version]}-%{[agent.hostname]}-%{+yyyy.MM.dd}"
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'